import { test,expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { bank,realCatalog,total,utility } from "./helpers";
const question=(id:string)=>realCatalog.questions.find(q=>q.id===id)!;
test("prova real com gráfico: pausa, recuperação, gabarito da versão e backup",async({page,browser,request})=>{
 await bank(page,"P2026A","Química",4);await page.getByRole("button",{name:"Criar prova do banco"}).click();await expect(page.getByText("P2026A-Q51",{exact:false})).toBeVisible();await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("radio",{name:"Alternativa B",exact:true}).check();await expect.poll(()=>total(page)).toBeGreaterThan(1000);await page.getByRole("button",{name:"Próxima questão →"}).click();await page.getByRole("radio",{name:"Alternativa A",exact:true}).check();await page.getByRole("button",{name:"Próxima questão →"}).click();
 const graph=question("P2026A-Q53");expect(graph.graph).toBe(true);const media=graph.audit!.media.find(m=>m.page===16)!;const image=page.locator(`.training-question img[src="${media.imageUrl}"]`);await expect(image).toBeVisible();expect(await image.evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(1400);expect((await(await request.get(media.pdfUrl)).body()).subarray(0,5).toString()).toBe("%PDF-");await page.getByRole("button",{name:/Ampliar.*página 16/}).click();await page.getByRole("button",{name:"+",exact:true}).click();await expect(page.getByText("150%",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Fechar imagem"}).click();await page.getByRole("radio",{name:"Alternativa D",exact:true}).check();await page.getByLabel("Marcar para revisar nesta tentativa").check();await page.getByRole("button",{name:"Pausar",exact:true}).click();await expect(page.getByRole("button",{name:"Iniciar ou retomar"})).toBeEnabled();const paused=await total(page);await page.waitForTimeout(1300);expect(await total(page)).toBe(paused);await page.reload();await expect(page.getByRole("radio",{name:"Alternativa D",exact:true})).toBeChecked();expect(await total(page)).toBe(paused);await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("button",{name:"Ir para questão 4",exact:true}).click();await page.getByRole("button",{name:"Finalizar prova",exact:true}).click();await page.getByRole("button",{name:"Confirmar finalização"}).click();
 await expect(page.getByTestId("summary-percentage")).toHaveText("50.0%");await expect(page.locator(".results-table tbody tr")).toHaveCount(4);for(const [i,result] of ["Acerto","Erro","Acerto","Em branco"].entries())await expect(page.locator(".results-table tbody tr").nth(i)).toContainText(result);
 await utility(page);const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Exportar backup"}).click()]);const backup=await readFile((await download.path())!),a=JSON.parse(backup.toString()).attempts[0];expect(a.items.map((q:{id:string})=>q.id)).toEqual(["P2026A-Q51","P2026A-Q52","P2026A-Q53","P2026A-Q54"]);for(const item of a.items)expect(item.audit).toEqual(question(item.id).audit);expect(a.totalMs).toBeGreaterThanOrEqual(paused);await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.locator(".error-entry")).toHaveCount(1);await expect(page.locator(".error-entry")).toContainText("P2026A-Q52");
 const restored=await browser.newContext();try{const p=await restored.newPage();await p.goto("/");await utility(p);await p.getByLabel("Arquivo de backup").setInputFiles({name:"real.json",mimeType:"application/json",buffer:backup});await p.getByRole("button",{name:"Provas",exact:true}).click();await p.getByRole("button",{name:"Ver relatório",exact:true}).click();await expect(p.getByTestId("summary-percentage")).toHaveText("50.0%");}finally{await restored.close();}
});
test("questão 1 das aplicações A e B mantém gabaritos E e A",async({page})=>{
 for(const [exam,outcome,key] of [["P2026A","Acerto","E"],["P2026B","Erro","A"]]){
  await bank(page,exam,"Língua Portuguesa");await page.getByRole("button",{name:"Criar prova do banco"}).click();await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("radio",{name:"Alternativa E",exact:true}).check();await page.getByRole("button",{name:"Finalizar prova",exact:true}).click();await page.getByRole("button",{name:"Confirmar finalização"}).click();await expect(page.locator(".results-table tbody tr")).toContainText(outcome);expect(question(`${exam}-Q01`).audit!.key!.answer).toBe(key);const detail=page.locator(".question-review-list .result-source").first();await detail.locator("summary").first().click();await expect(detail).toContainText(key);
 }
});
test("prova reservada exige inclusão; terceiros e chave não pareada permanecem separados",async({page})=>{
 await bank(page,"P2026C","Matemática",1);await expect(page.getByText("0 disponíveis · 1 solicitadas · faltam 1")).toBeVisible();await page.getByText("Conteúdo reservado para avaliação",{exact:true}).click();await page.getByLabel("Incluir reservadas para avaliação",{exact:false}).check();await expect(page.getByText("15 disponíveis · 1 solicitadas")).toBeVisible();await page.getByLabel("Incluir reservadas para avaliação",{exact:false}).uncheck();await page.getByLabel("Origem do banco",{exact:true}).selectOption("third-party");await page.getByLabel("Prova de origem",{exact:true}).selectOption("S2026B");await expect(page.getByText("15 disponíveis · 1 solicitadas")).toBeVisible();await page.getByLabel("Prova de origem",{exact:true}).selectOption("S2026A");await expect(page.getByRole("button",{name:"Criar prova do banco"})).toBeDisabled();
});
