import { test,expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { importAttempts,knownAttempt,realCatalog,utility } from "./helpers";
const math=realCatalog.questions.filter(q=>q.examId==="P2026A"&&q.discipline==="Matemática").slice(0,10);
function known(){const a=knownAttempt(math.slice(0,2),new Set([math[0].id]),new Set([math[1].id]),"duas-questoes","2026-10-01T15:00:00Z",60000),b=knownAttempt(math,new Set(math.slice(1).map(q=>q.id)),new Set(),"dez-questoes","2026-10-02T15:00:00Z",30000);return [a,b];}
test("pedidos inéditos são configurações salvas, sem geração fictícia ou banco automático",async({page})=>{
 await page.goto("/");await expect(page.getByRole("button",{name:"Gerar prova inédita"})).toBeDisabled();await page.getByRole("button",{name:"Prova personalizada",exact:true}).click();await page.getByLabel("Escreva o que quer praticar").fill("5 questões de matemática; 20 questões de português");await page.getByRole("button",{name:"Aplicar pedido"}).click();await expect(page.getByLabel("Quantidade 1",{exact:true})).toHaveValue("5");await expect(page.getByLabel("Quantidade 2",{exact:true})).toHaveValue("20");await page.getByRole("button",{name:"Salvar configuração"}).click();await expect(page.locator(".saved-configurations .compact-card")).toHaveCount(1);await expect(page.locator(".attempt-list article")).toHaveCount(0);await page.reload();await expect(page.locator(".saved-configurations .compact-card")).toHaveCount(1);
});
test("consolidado ponderado 10/12, repetidas e primeira resposta; andamento não entra",async({page})=>{
 await page.goto("/");await importAttempts(page,known());await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.getByTestId("summary-percentage")).toHaveText("83.3%");await expect(page.getByTestId("summary-correct")).toHaveText("10 / 12 acertos");await expect(page.getByTestId("summary-wrong")).toHaveText("1");await expect(page.getByTestId("summary-blank")).toHaveText("1");await expect(page.getByTestId("summary-time")).toHaveText("00:07:00");await expect(page.getByTestId("summary-average")).toHaveText("00:00:35");await expect(page.getByText("2 ocorrências repetidas")).toBeVisible();
 await page.getByLabel("Somente a primeira resposta a cada questão").check();await expect(page.getByTestId("summary-correct")).toHaveText("10 / 10 acertos");await expect(page.getByTestId("summary-percentage")).toHaveText("100.0%");await page.getByLabel("Período inicial").fill("2026-10-02");await expect(page.getByTestId("summary-correct")).toHaveText("9 / 9 acertos");await page.getByRole("button",{name:"Limpar filtros",exact:true}).click();await expect(page.getByTestId("summary-correct")).toHaveText("10 / 12 acertos");await page.getByLabel("Matéria da revisão").selectOption("Ciências da Natureza");await expect(page.getByTestId("summary-percentage")).toHaveText("Dados insuficientes");
});
test("motivo de erro, simulação e lista de revisão integrada preservam resultado",async({page})=>{
 await page.goto("/");await importAttempts(page,known());await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.locator(".error-entry")).toHaveCount(1);const reason=page.getByLabel(/^Motivo do erro /);await reason.selectOption("interpretação");await expect(reason).toBeEnabled();await page.getByRole("button",{name:"Selecionar todos os erros"}).click();await expect(page.locator(".scenario")).toContainText("91.7%");await expect(page.locator(".scenario")).toContainText("1 acertos adicionais em 12 questões avaliáveis");await page.getByRole("button",{name:/Criar lista de revisão/}).click();await expect(page.getByRole("heading",{name:"Revisão · 1 erros selecionados"})).toBeVisible();await expect(page.getByText(math[0].id,{exact:false})).toBeVisible();await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.getByTestId("summary-correct")).toHaveText("10 / 12 acertos");await expect(page.getByLabel(/^Motivo do erro /)).toHaveValue("interpretação");
});
test("meta, pesos pessoais e novos dados restauram com backup",async({page,browser})=>{
 await page.goto("/");await importAttempts(page,known());await page.getByLabel("Meta geral (%)").fill("90");await page.getByLabel("Curso para nota ponderada").fill("Meu curso");await page.getByLabel("Peso de Matemática",{exact:true}).fill("1");await page.getByRole("button",{name:"Salvar metas e pesos"}).click();await expect(page.getByText("Metas e pesos salvos neste navegador.")).toBeVisible();
 const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Exportar backup"}).click()]);const backup=await readFile((await download.path())!);const b=JSON.parse(backup.toString());expect(b.preferences[0].goalPercentage).toBe(90);expect(b.attempts[0].telemetry).toBeUndefined();
 const ctx=await browser.newContext();try{const p=await ctx.newPage();await p.goto("/");await utility(p);await p.getByLabel("Arquivo de backup").setInputFiles({name:"report.json",mimeType:"application/json",buffer:backup});await p.getByRole("button",{name:"Revisão",exact:true}).click();await expect(p.getByText("Faltam 6.7 pontos percentuais neste recorte.")).toBeVisible();await expect(p.getByText("83.3 / 100",{exact:true})).toBeVisible();await expect(p.getByText("Registros antigos permanecem indisponíveis.",{exact:false})).toBeVisible();}finally{await ctx.close();}
});
for(const viewport of [{width:1440,height:1000},{width:390,height:844}])test(`configuração, prova com gráfico e relatórios em ${viewport.width}px`,async({page})=>{
 await page.setViewportSize(viewport);await page.goto("/");await expect(page.getByRole("heading",{name:"Como você quer praticar?"})).toBeVisible();await page.screenshot({path:`/tmp/insper-v3-config-${viewport.width}.png`,fullPage:true});await importAttempts(page,known());await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.getByTestId("summary-percentage")).toHaveText("83.3%");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`/tmp/insper-v3-review-${viewport.width}.png`,fullPage:true});await page.getByRole("button",{name:"Provas",exact:true}).click();await page.getByRole("button",{name:"Ver relatório",exact:true}).first().click();await expect(page.getByTestId("summary-percentage")).toHaveText("90.0%");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`/tmp/insper-v3-result-${viewport.width}.png`,fullPage:true});
 await page.getByRole("button",{name:"← Voltar a Provas",exact:true}).click();await page.getByRole("button",{name:/^Banco conferido/}).click();await page.getByRole("button",{name:"Prova personalizada",exact:true}).click();await page.getByLabel("Prova de origem",{exact:true}).selectOption("P2026A");await page.getByLabel("Matéria 1",{exact:true}).selectOption("Ciências da Natureza");await page.getByLabel("Disciplina 1",{exact:true}).selectOption("Química");await page.getByLabel("Assunto 1",{exact:true}).selectOption("Cinética e catálise");await page.getByLabel("Quantidade 1",{exact:true}).fill("1");await page.getByRole("button",{name:"Criar prova do banco"}).click();await expect(page.getByRole("button",{name:"Iniciar ou retomar"})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`/tmp/insper-v3-question-${viewport.width}.png`,fullPage:true});
});

test("prova completa do banco cria 60 itens com 15 por área e não conta andamento",async({page})=>{
 await page.goto("/");await page.getByRole("button",{name:"Banco conferido",exact:true}).click();await page.getByLabel("Prova de origem",{exact:true}).selectOption("P2026A");await page.getByRole("button",{name:"Criar prova do banco"}).click();await expect(page.getByRole("button",{name:"Iniciar ou retomar"})).toBeEnabled();await expect(page.locator(".question-nav button")).toHaveCount(60);
 await utility(page);const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Exportar backup"}).click()]);const a=JSON.parse(await readFile((await download.path())!,"utf8")).attempts[0];expect(a.kind).toBe("full");expect(a.items).toHaveLength(60);
 const areas:{[key:string]:number}={};for(const item of a.items){const area=item.discipline==="Matemática"?"Matemática":item.discipline==="Língua Portuguesa"?"Português":["História","Geografia","Sociologia","Filosofia"].includes(item.discipline)?"Humanas":"Natureza";areas[area]=(areas[area]??0)+1;}expect(areas).toEqual({Matemática:15,Português:15,Humanas:15,Natureza:15});await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.getByTestId("summary-correct")).toHaveText("0 / 0 acertos");await expect(page.getByTestId("summary-percentage")).toHaveText("Dados insuficientes");
});

test("simulados completos comparáveis têm radar de quatro áreas e última média de 62,5%",async({page})=>{
 const aQuestions=realCatalog.questions.filter(q=>q.examId==="P2026A"),bQuestions=realCatalog.questions.filter(q=>q.examId==="P2026B");
 const a=knownAttempt(aQuestions,new Set(aQuestions.slice(0,30).map(q=>q.id)),new Set(),"completo-a","2026-10-01T15:00:00Z",1000),b=knownAttempt(bQuestions,new Set(bQuestions.slice(0,45).map(q=>q.id)),new Set(),"completo-b","2026-10-02T15:00:00Z",2000);
 await page.goto("/");await importAttempts(page,[a,b]);await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.getByTestId("summary-correct")).toHaveText("75 / 120 acertos");await expect(page.getByTestId("summary-percentage")).toHaveText("62.5%");await expect(page.locator(".chronology-group h3").first()).toHaveText("Simulados completos");await expect(page.locator(".radar polygon")).toHaveCount(6);await expect(page.locator(".history-summary")).toContainText("62.5%");await expect(page.locator(".history-summary")).toContainText("2 provas com questões novas na amostra · 120 questões");await expect(page.locator(".area-card")).toHaveCount(4);
});
