import { test,expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { bank,fixtures,total,utility } from "./helpers";
test("quantidade insuficiente não muda assunto",async({page})=>{
 await bank(page,"","Matemática",5);await page.getByLabel("Assunto 1",{exact:true}).selectOption("Sistemas lineares");await expect(page.getByText("2 disponíveis · 5 solicitadas · faltam 3")).toBeVisible();await expect(page.getByRole("button",{name:"Criar prova do banco"})).toBeDisabled();
});
test("respostas, visitas, mudanças, pausa, recuperação, relatório e backup",async({page,context,browser})=>{
 await fixtures(context);await bank(page,"","Matemática",3);await page.getByRole("button",{name:"Criar prova do banco"}).click();await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("radio",{name:"Alternativa A",exact:true}).check();await expect.poll(()=>total(page)).toBeGreaterThan(1000);
 await page.getByRole("button",{name:"Próxima questão →"}).click();await page.getByRole("radio",{name:"Alternativa C",exact:true}).check();await page.getByRole("radio",{name:"Alternativa A",exact:true}).check();await page.getByLabel("Marcar para revisar nesta tentativa").check();await page.getByRole("button",{name:"Pausar",exact:true}).click();await expect(page.getByRole("button",{name:"Iniciar ou retomar"})).toBeEnabled();
 const paused=await total(page);await page.waitForTimeout(1300);expect(await total(page)).toBe(paused);await page.reload();await expect(page.getByRole("radio",{name:"Alternativa A",exact:true})).toBeChecked();await expect(page.getByLabel("Marcar para revisar nesta tentativa")).toBeChecked();expect(await total(page)).toBe(paused);
 await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("button",{name:"← Questão anterior",exact:true}).click();await page.getByRole("button",{name:"Ir para questão 3",exact:true}).click();await page.getByRole("button",{name:"Finalizar prova",exact:true}).click();await page.getByRole("button",{name:"Confirmar finalização"}).click();
 await expect(page.getByTestId("summary-percentage")).toHaveText("33.3%");await expect(page.locator(".results-table tbody tr")).toHaveCount(3);await expect(page.getByTestId("summary-wrong")).toHaveText("1");await expect(page.getByTestId("summary-blank")).toHaveText("1");await page.getByRole("button",{name:"Revisão",exact:true}).click();await expect(page.locator(".error-entry")).toHaveCount(1);
 const reason=page.getByLabel(/^Motivo do erro /);await reason.selectOption("cálculo");await expect(reason).toBeEnabled();await utility(page);const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"Exportar backup"}).click()]);const backup=await readFile((await download.path())!),parsed=JSON.parse(backup.toString());expect(parsed.schemaVersion).toBe(3);expect(parsed.attempts).toHaveLength(1);expect(parsed.errorNotes[0].reason).toBe("cálculo");expect(parsed.attempts[0].telemetry.answerChanges["TEST-Q2"]).toBe(1);expect(parsed.attempts[0].telemetry.visits["TEST-Q1"]).toBe(2);expect(Object.values(parsed.attempts[0].timesMs).reduce<number>((s,v)=>s+Number(v),0)).toBeCloseTo(parsed.attempts[0].totalMs);
 const restored=await browser.newContext();try{await fixtures(restored);const p=await restored.newPage();await p.goto("/");await utility(p);await p.getByLabel("Arquivo de backup").setInputFiles({name:"restored.json",mimeType:"application/json",buffer:backup});await p.getByRole("button",{name:"Revisão",exact:true}).click();await expect(p.getByTestId("summary-percentage")).toHaveText("33.3%");await expect(p.getByLabel(/^Motivo do erro /)).toHaveValue("cálculo");}finally{await restored.close();}
});
test("reserva é explícita, consulta sem chave e imagem amplia",async({page,context})=>{
 await fixtures(context);await page.goto("/");await utility(page,"Fontes e acervo");await expect(page.locator(".question-card").filter({hasText:"TEST-Q5"})).toContainText("Completa · sem correção");await bank(page,"","Matemática",4);await expect(page.getByText("3 disponíveis · 4 solicitadas · faltam 1")).toBeVisible();await page.getByText("Conteúdo reservado para avaliação",{exact:true}).click();await page.getByLabel("Incluir reservadas para avaliação",{exact:false}).check();await expect(page.getByText("4 disponíveis · 4 solicitadas")).toBeVisible();await page.getByLabel("Quantidade 1",{exact:true}).fill("1");await page.getByRole("button",{name:"Criar prova do banco"}).click();await page.getByRole("button",{name:/Ampliar/}).click();await expect(page.getByRole("dialog")).toBeVisible();await page.getByRole("button",{name:"+",exact:true}).click();await expect(page.getByText("150%",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Fechar imagem"}).click();await expect(page.getByRole("link",{name:"Abrir página original"})).toHaveAttribute("href","/sources/fixture.pdf#page=1");
});
test("backup v1 mantém marcações",async({page})=>{
 await page.goto("/");await utility(page);const old={app:"insper-pessoal",schemaVersion:1,exportedAt:new Date().toISOString(),bookmarks:[{questionId:"P2019-Q01",savedAt:new Date().toISOString()}]};await page.getByLabel("Arquivo de backup").setInputFiles({name:"v1.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(old))});await expect(page.getByText("1 marcação local")).toBeVisible();await page.reload();await utility(page);await expect(page.getByText("1 marcação local")).toBeVisible();
});
test("fechar aba ativa recupera pausada sem cobrar tempo fechado",async({page,context})=>{
 await fixtures(context);await bank(page);await page.getByRole("button",{name:"Criar prova do banco"}).click();await page.getByRole("button",{name:"Iniciar ou retomar"}).click();await page.getByRole("radio",{name:"Alternativa A",exact:true}).check();await expect.poll(()=>total(page)).toBeGreaterThan(1200);const before=await total(page);await page.close();await new Promise(r=>setTimeout(r,1600));const reopened=await context.newPage();await reopened.goto("/");await expect(reopened.getByRole("button",{name:"Iniciar ou retomar"})).toBeEnabled();await expect(reopened.getByRole("radio",{name:"Alternativa A",exact:true})).toBeChecked();const recovered=await total(reopened);expect(recovered).toBeLessThan(before+1000);await reopened.waitForTimeout(1200);expect(await total(reopened)).toBe(recovered);
});
