"use client";
import { useMemo,useState } from "react";
import { areas, disciplinesByArea, originLabels, type Area } from "@/domain/classification";
import { uniqueOptions } from "@/domain/catalog";
import { allocatePlan, defaultPlan, fullLines, parseRequest, validatePlan, type ProofPlan, type SavedPlan } from "@/domain/proof-plan";
import { formatTime, gradeAttempt, type Attempt } from "@/domain/training";
import type { Catalog } from "@/domain/types";
import type { ChatGPTController } from "@/hooks/useChatGPT";
import ChatGPTConnection from "./ChatGPTConnection";
export default function ProofsPanel({catalog,attempts,plans,storageReady,onCreate,onOpen,onSavePlan,onDeletePlan,ai}:{catalog:Catalog;attempts:Attempt[];plans:SavedPlan[];storageReady:boolean;onCreate:(plan:ProofPlan)=>Promise<void>;onOpen:(id:string)=>void;onSavePlan:(plan:ProofPlan)=>Promise<void>;onDeletePlan:(id:string)=>Promise<void>;ai:ChatGPTController}){
  const [plan,setPlan]=useState<ProofPlan>(defaultPlan),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[historyStatus,setHistoryStatus]=useState("");
  const total=plan.lines.reduce((n,l)=>n+l.quantity,0),valid=validatePlan(plan),allocations=useMemo(()=>allocatePlan(plan,catalog.questions),[plan,catalog]);
  const missing=allocations.reduce((n,a)=>n+a.missing,0);
  async function action(fn:()=>Promise<void>,success=""){setBusy(true);setMessage("");try{await fn();setMessage(success);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
  function mode(value:ProofPlan["mode"]){setPlan(p=>({...p,mode:value,lines:value==="full"?fullLines():[{area:"Matemática",discipline:"Matemática",topic:"",quantity:5}]}));setMessage("");}
  function interpret(){try{const lines=parseRequest(plan.prompt,catalog.questions);const full=lines.length===4&&areas.every(a=>lines.some(l=>l.area===a&&l.quantity===15&&!l.discipline&&!l.topic));setPlan(p=>({...p,lines,mode:full?"full":"custom"}));setMessage("Pedido interpretado. Confira as matérias, os assuntos e as quantidades abaixo.");}catch(e){setMessage(e instanceof Error?e.message:"Pedido não reconhecido.");}}
  const completed=attempts.filter(a=>a.status==="completed").length;
  const generating=!!ai.job&&["generating","reviewing"].includes(ai.job.status);
  function firstTest(){const next:ProofPlan={mode:"custom",origin:"ai",examId:"",includeReserved:false,prompt:"3 questões de sistemas lineares",lines:[{area:"Matemática",discipline:"Matemática",topic:"Sistemas lineares",quantity:3}]};setPlan(next);void action(()=>onCreate(next));}
  return <section aria-label="Provas"><div className="page-heading"><div><span className="eyebrow">Insper · 2027.1</span><h1>Uma prova. Seu próximo passo.</h1><p>Configure, responda no seu ritmo e descubra onde avançar.</p></div><div className="heading-status"><strong>{completed}</strong><span>provas finalizadas</span></div></div>
    <div className="proof-builder panel"><div className="builder-heading"><div><span className="eyebrow">Nova prova</span><h2>Como você quer praticar?</h2></div><span className="pill">{total} questões</span></div>
      <div className="origin-picker" role="group" aria-label="Origem da nova prova"><button aria-label="Inéditas por IA" className={plan.origin==="ai"?"source-option selected":"source-option"} aria-pressed={plan.origin==="ai"} onClick={()=>setPlan(p=>({...p,origin:"ai",examId:""}))}><span className="option-icon" aria-hidden="true">✦</span><strong>Inéditas por IA</strong><small>Questões autorais, criadas para seu objetivo</small><span className="tag">Objetivo principal</span></button>
        <button aria-label="Banco conferido" className={plan.origin!=="ai"?"source-option selected secondary":"source-option secondary"} aria-pressed={plan.origin!=="ai"} onClick={()=>setPlan(p=>({...p,origin:"official",examId:""}))}><span className="option-icon" aria-hidden="true">▤</span><strong>Banco conferido</strong><small>Questões existentes, com fontes e gabaritos</small></button></div>
      <div className="mode-switch" role="group" aria-label="Formato da prova"><button aria-pressed={plan.mode==="full"} className={plan.mode==="full"?"active":""} onClick={()=>mode("full")}>Prova completa</button><button aria-pressed={plan.mode==="custom"} className={plan.mode==="custom"?"active":""} onClick={()=>mode("custom")}>Prova personalizada</button></div>
      {plan.mode==="full"?<div className="composition"><p>60 questões com a composição do seu simulado.</p><div className="composition-grid">{areas.map(a=><div key={a}><strong>15</strong><span>{a}</span></div>)}</div></div>:<>
        <div className="request-input"><label htmlFor="natural-request">Escreva o que quer praticar</label><div><input id="natural-request" value={plan.prompt} maxLength={3000} onChange={e=>setPlan(p=>({...p,prompt:e.target.value}))} placeholder="5 questões de matemática; 20 questões de português"/><button onClick={interpret}>Aplicar pedido</button></div><p className="muted">O pedido configura a prova. A geração inédita depende da conexão com a IA.</p></div>
        <div className="plan-lines">{plan.lines.map((line,index)=>{const topics=uniqueOptions(catalog.questions.filter(q=>disciplinesByArea[line.area].includes(q.discipline)&&(!line.discipline||q.discipline===line.discipline)).map(q=>q.topic));return <div className="plan-line" key={index}>
          <label>Matéria<select aria-label={`Matéria ${index+1}`} value={line.area} onChange={e=>setPlan(p=>({...p,lines:p.lines.map((l,i)=>i===index?{...l,area:e.target.value as Area,discipline:"",topic:""}:l)}))}>{areas.map(a=><option key={a}>{a}</option>)}</select></label>
          <label>Disciplina<select aria-label={`Disciplina ${index+1}`} value={line.discipline} onChange={e=>setPlan(p=>({...p,lines:p.lines.map((l,i)=>i===index?{...l,discipline:e.target.value,topic:""}:l)}))}><option value="">Todas da matéria</option>{disciplinesByArea[line.area].map(d=><option key={d}>{d}</option>)}</select></label>
          <label>Assunto<select aria-label={`Assunto ${index+1}`} value={line.topic} onChange={e=>setPlan(p=>({...p,lines:p.lines.map((l,i)=>i===index?{...l,topic:e.target.value}:l)}))}><option value="">Todos os assuntos</option>{topics.map(t=><option key={t}>{t}</option>)}</select></label>
          <label>Quantidade<input aria-label={`Quantidade ${index+1}`} type="number" min="1" max="400" value={line.quantity} onChange={e=>setPlan(p=>({...p,lines:p.lines.map((l,i)=>i===index?{...l,quantity:Number(e.target.value)}:l)}))}/></label>
          <button aria-label={`Remover matéria ${index+1}`} disabled={plan.lines.length===1} onClick={()=>setPlan(p=>({...p,lines:p.lines.filter((_,i)=>i!==index)}))}>×</button>
        </div>;})}</div><button className="text-button" disabled={plan.lines.length>=30} onClick={()=>setPlan(p=>({...p,lines:[...p.lines,{area:"Português",discipline:"Língua Portuguesa",topic:"",quantity:5}]}))}>+ Adicionar matéria ou assunto</button>
      </>}
      {plan.origin!=="ai"&&<div className="bank-options"><div className="form-grid"><label>Origem do banco<select aria-label="Origem do banco" value={plan.origin} onChange={e=>setPlan(p=>({...p,origin:e.target.value as ProofPlan["origin"],examId:""}))}><option value="official">Questões oficiais · Insper/Vunesp</option><option value="third-party">Simulados de terceiros · ALFRED</option></select></label>
        <label>Prova de origem<select aria-label="Prova de origem" value={plan.examId} onChange={e=>setPlan(p=>({...p,examId:e.target.value}))}><option value="">Todas desta origem</option>{catalog.exams.filter(e=>e.origin===plan.origin).map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label></div>
        <details><summary>Conteúdo reservado para avaliação</summary><label className="checkbox"><input type="checkbox" checked={plan.includeReserved} onChange={e=>setPlan(p=>({...p,includeReserved:e.target.checked}))}/>Incluir reservadas para avaliação (expõe esse conteúdo)</label></details>
        <div className="availability-lines" aria-label="Disponibilidade por matéria">{allocations.map(a=><p key={a.index}><span>{a.line.topic||a.line.discipline||a.line.area}</span><strong>{a.available} disponíveis · {a.line.quantity} solicitadas{a.missing?` · faltam ${a.missing}`:""}</strong></p>)}</div>
        <p className="muted">{originLabels[plan.origin]}. Estas questões já existem no banco. {missing?`Faltam ${missing} para essa composição; outro assunto não será acrescentado.`:"A lista usará somente as questões completas com gabarito conferido."}</p>
      </div>}
      {plan.origin==="ai"&&<ChatGPTConnection ai={ai} onTest={firstTest} existingIds={[...new Set(attempts.flatMap(a=>a.items.map(i=>i.id)))].slice(-5000)}/>}
      <div className="builder-footer"><div>{plan.origin==="ai"?<><strong>{ai.connection?.status==="connected"?"Questões criadas e revisadas por IA":"Conecte para gerar questões inéditas"}</strong><p>Geração em lotes. A prova abre quando todas as questões forem revisadas.</p></>:<><strong>{total} questões · banco conferido</strong><p>Seu histórico será salvo durante a prova.</p></>}</div><div className="button-row"><button disabled={!storageReady||busy||!valid} onClick={()=>void action(()=>onSavePlan(plan),"Configuração salva em Provas. Ainda não é uma prova gerada.")}>Salvar configuração</button>
        <button className="primary" disabled={!storageReady||busy||!valid||(plan.origin==="ai"?generating:missing>0)} onClick={()=>void action(()=>onCreate(plan))}>{busy?"Preparando…":generating&&plan.origin==="ai"?"Gerando e revisando…":plan.origin==="ai"?"Gerar prova inédita":"Criar prova do banco"}</button></div></div>
      {message&&<p role="status" className="feedback">{message}</p>}
    </div>
    {plans.length>0&&<section className="saved-configurations"><div className="section-heading"><h2>Configurações salvas</h2><span className="muted">Pedidos prontos para continuar</span></div><div className="saved-grid">{plans.map(saved=><article className="panel compact-card" key={saved.id}><span className="eyebrow">{originLabels[saved.plan.origin]}</span><h3>{saved.title}</h3><p>{saved.plan.lines.reduce((n,l)=>n+l.quantity,0)} questões · configuração{saved.plan.origin==="ai"?" para gerar":" do banco"}</p><div className="button-row"><button onClick={()=>{setPlan(structuredClone(saved.plan));setMessage("Configuração carregada. Confira e prossiga.");window.scrollTo({top:0,behavior:"smooth"});}}>Usar configuração</button><button aria-label={`Excluir configuração ${saved.title}`} onClick={()=>void action(()=>onDeletePlan(saved.id))}>Excluir</button></div></article>)}</div></section>}
    <section className="proof-history"><div className="section-heading"><div><span className="eyebrow">Salvas neste navegador</span><h2>Suas provas</h2></div><label>Status das provas<select value={historyStatus} onChange={e=>setHistoryStatus(e.target.value)}><option value="">Todas</option><option value="paused">Em andamento</option><option value="completed">Finalizadas</option></select></label></div>
      {!attempts.length?<div className="empty-state"><span className="empty-symbol">▤</span><h3>A primeira prova começa aqui.</h3><p>Crie uma prova do banco ou salve seu pedido de questões inéditas.</p></div>:<div className="attempt-list">{[...attempts].filter(a=>!historyStatus||a.status===historyStatus).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(a=><article key={a.id}><div><span className="eyebrow">{a.kind==="full"?"Simulado completo":a.kind==="review"?"Lista de revisão":"Lista temática"}</span><h3>{a.title}</h3><p>{a.items.length} questões · {formatTime(a.totalMs)} ativo · {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(a.createdAt))}</p></div><div className="attempt-status"><span className={`tag ${a.status==="completed"?"green":""}`}>{a.status==="completed"?`${gradeAttempt(a).percentage.toFixed(1)}% · finalizada`:"Em andamento · pausada"}</span><button onClick={()=>onOpen(a.id)}>{a.status==="completed"?"Ver relatório":"Continuar prova"}</button></div></article>)}</div>}
    </section>
  </section>;
}
